FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y tomcat8

ENV CATALINA_HOME /usr/share/tomcat8
ENV PATH $CATALINA_HOME/bin:$PATH

RUN mkdir -p $CATALINA_HOME/conf && \
    cp -R /etc/tomcat8/* $CATALINA_HOME/conf && \
    mkdir $CATALINA_HOME/webapps/ 

EXPOSE 8080
CMD ["catalina.sh", "run"]

