FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y tomcat8
#ENV CATALINA_HOME="/usr/share/tomcat8"
RUN mkdir -p /usr/share/tomcat8/conf && cp -R /etc/tomcat8/* /usr/share/tomcat8/conf
RUN apt-get install -y maven
RUN apt-get install -y git
RUN cd /opt/;git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
RUN cd /opt/boxfuse-sample-java-war-hello/;mvn package
RUN mkdir /usr/share/tomcat8/webapps/ && cp /opt/boxfuse-sample-java-war-hello/target/hello-1.0.war /usr/share/tomcat8/webapps/hello-1.0.war

EXPOSE 8080
CMD ["/usr/share/tomcat8/bin/catalina.sh", "run"]
